name: "hikari"
description: "Fluid, responsive blog theme for Jekyll"

author: "John Doge"

url: "http://m3xm.github.io"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
